name: Build and Upload Binaries

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.22

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -o mini-updater-linux-amd64
        GOOS=linux GOARCH=arm64 go build -o mini-updater-linux-arm64

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -o mini-updater-windows-amd64.exe
        GOOS=windows GOARCH=arm64 go build -o mini-updater-windows-arm64.exe

    - name: Upload binaries
      uses: actions/upload-artifact@v3
      with:
        name: mini-updater-binaries
        path: |
          mini-updater-linux-amd64
          mini-updater-linux-arm64
          mini-updater-windows-amd64.exe
          mini-updater-windows-arm64.exe